version: "3"

services:
  db:
    image: postgres:12
    container_name: lolinfo_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/lolinfo.sql:/docker-entrypoint-initdb.d/lolinfo.sql
    environment:
      - PGDATA=/srv/data
      - POSTGRES_PASSWORD=${PGPASSWORD}
